service: tflambdaIMG

provider:
  name: aws
  region: eu-west-1
  runtime: python3.6
  stage: dev
  credentials:
    accessKeyId: 
    secretAccessKey: 

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - ${self:provider.environment.BUCKET}
           - "/*"

  environment:
    BUCKET: serverless-ml-2

functions:
  infer:
    handler: infer.inferHandler
    timeout: 30
    events:
      - http:
          path: infer
          method: post
          
  inferqueue:
    handler: inferqueue.inferqueueHandler
    timeout: 30
    events:
      - http:
          path: inferqueue
          method: post
          
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard

package:
  exclude:
    - "*.gz"

resources:
  Resources:
    SageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
